GET http://localhost:8080/escuela-rest-api/v1/info

###
GET http://localhost:8080/escuela-rest-api/v1/alumnos

###
POST http://localhost:8080/escuela-rest-api/v1/calificaciones
Content-Type: application/json

{
    "idAlumno":8,
    "idMateria":4,
    "calificacion": "6.5"
}


###
GET http://localhost:8080/escuela-rest-api/v1/calificaciones?idAlumno=1
Content-Type: application/json

###
DELETE http://localhost:8080/escuela-rest-api/v1/
Content-Type: application/json