GET http://localhost:8080/escuela-rest-api/v1/info

###
GET http://localhost:8080/escuela-rest-api/v1/alumnos

###
GET http://localhost:8080/escuela-rest-api/v1/alumnos/1/boleta

###
POST http://localhost:8080/escuela-rest-api/v1/calificaciones
Content-Type: application/json

{
    "idAlumno":1,
    "idMateria":3,
    "calificacion": "6"
}

###
GET http://localhost:8080/escuela-rest-api/v1/calificaciones?idAlumno=1
Content-Type: application/json

###
PUT http://localhost:8080/escuela-rest-api/v1/calificaciones
Content-Type: application/json

{
    "idAlumno":1,
    "idMateria":1,
    "calificacion": "6"
}

###
DELETE  http://localhost:8080/escuela-rest-api/v1/calificaciones/2
Content-Type: application/json
