server:
    port: 8080
    servlet:
        context-path: /escuela-rest-api/v1

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/escuela
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver 
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true

logging:
    level:
        org:
            hibernate:
                SQL: debug

uris-cors-config-front: http://localhost:4200, https://dev.com.mx
